### Exercise 1

In [5]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a = a.transpose()
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [7]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

### Exercise 2

In [8]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

### Exercise 3

In [34]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]
a_centered_sp

8.0

In [31]:
a_centered_sp / (a_centered.shape[0] - 1)

2

### Exercise 4

In [45]:
s = np.cov(a.T)
s [0, 1]


2.0